### ISSUE TITLE
The method 'call' was called on null.

### ISSUE THREAD

**Issue by loonix** [tkortekaas/pinch_zoom#4]
Hi,

First of all, thanks for the cool plugin!

I am facing a weird issue not sure if you can help me. I have implemented the plugin in my code and each time just press to zoom it throws this error message:
`The method 'call' was called on null.`

Here is my code:
```dart
 Scaffold(
          // (....)
          body: PinchZoom(
            image: Image.file(imagePath),
            zoomedBackgroundColor: Colors.black.withOpacity(0.5),
            resetDuration: const Duration(milliseconds: 100),
            maxScale: 2.5,
          ),
          // (....)
```

Error Log:
```powershell
════════════════════════════════════════════════════════════════════════════════
E/flutter (12662): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter (12662): Receiver: null
E/flutter (12662): Tried calling: call()
E/flutter (12662): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
E/flutter (12662): #1      _PinchZoomState._show 
package:pinch_zoom/src/pinch_zoom_widget.dart:181
E/flutter (12662): #2      _PinchZoomState.build.<anonymous closure>.<anonymous closure> 
package:pinch_zoom/src/pinch_zoom_widget.dart:63
E/flutter (12662): #3      new Future.delayed.<anonymous closure>  (dart:async/future.dart:326:39)
E/flutter (12662): #4      _rootRun  (dart:async/zone.dart:1182:47)
E/flutter (12662): #5      _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (12662): #6      _CustomZone.runGuarded  (dart:async/zone.dart:997:7)
E/flutter (12662): #7      _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)
E/flutter (12662): #8      _rootRun  (dart:async/zone.dart:1190:13)
E/flutter (12662): #9      _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (12662): #10     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:1021:23)
E/flutter (12662): #11     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:18:15)
E/flutter (12662): #12     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (12662): #13     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (12662): #14     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (12662):

════════ Exception caught by widgets library ═══════════════════════════════════
```

**Comment by tkortekaas** [comment]
Thank you for reporting the issue. This bug is now fixed in the 0.0.3 release
